// Netscape cookies.txt serialization for the Karaoke Submitter extension.
//
// Pure, dependency-free, and free of any `chrome.*` reference so it can be unit
// tested under `bun test` (see cookies.test.js). The service worker imports
// `serializeNetscapeCookies` and POSTs the result to the coordinator's
// `/cookies/youtube` endpoint (issue #73).

const NETSCAPE_HEADER =
  "# Netscape HTTP Cookie File\n" +
  "# Generated by the Karaoke Submitter extension. Do not edit.\n";

// yt-dlp treats a 0 expiry as a session cookie. Cap absurd far-future values to
// a 32-bit timestamp so the jar stays portable.
const MAX_EXPIRY = 2147483647;

function netscapeDomain(cookie) {
  // Host-only cookies (cookie.hostOnly === true) keep a bare domain and
  // include-subdomains FALSE; otherwise the domain carries a leading dot and
  // include-subdomains TRUE. Chrome already stores the leading dot for
  // domain-scoped cookies, but normalise defensively.
  let domain = String(cookie.domain || "");
  const includeSub = cookie.hostOnly ? "FALSE" : "TRUE";
  if (!cookie.hostOnly && !domain.startsWith(".")) {
    domain = "." + domain;
  }
  if (cookie.hostOnly && domain.startsWith(".")) {
    domain = domain.slice(1);
  }
  return { domain, includeSub };
}

function netscapeExpiry(cookie) {
  if (cookie.session || !cookie.expirationDate) {
    return 0;
  }
  const value = Math.floor(Number(cookie.expirationDate));
  if (!Number.isFinite(value) || value <= 0) {
    return 0;
  }
  return Math.min(value, MAX_EXPIRY);
}

// Serialize one Chrome cookie object into a single Netscape data line, or null
// if it cannot be represented (missing name/domain). httpOnly cookies get
// yt-dlp's `#HttpOnly_` domain prefix so they survive the round-trip — the
// YouTube auth cookies (SID/HSID/SSID/__Secure-*) are httpOnly and essential.
function cookieToNetscapeLine(cookie) {
  if (!cookie || !cookie.name || !cookie.domain) {
    return null;
  }
  const { domain, includeSub } = netscapeDomain(cookie);
  const prefix = cookie.httpOnly ? "#HttpOnly_" : "";
  const path = cookie.path || "/";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  const expiry = netscapeExpiry(cookie);
  // Tab-separated, exactly 7 fields. Strip stray tabs/newlines from value so a
  // single cookie can never break the field layout.
  const value = String(cookie.value || "").replace(/[\t\r\n]/g, "");
  return [
    `${prefix}${domain}`,
    includeSub,
    path,
    secure,
    String(expiry),
    cookie.name,
    value,
  ].join("\t");
}

// Serialize an array of Chrome cookie objects into a Netscape cookies.txt blob.
function serializeNetscapeCookies(cookies) {
  const lines = [];
  for (const cookie of cookies || []) {
    const line = cookieToNetscapeLine(cookie);
    if (line) {
      lines.push(line);
    }
  }
  return NETSCAPE_HEADER + lines.join("\n") + (lines.length ? "\n" : "");
}

export {
  serializeNetscapeCookies,
  cookieToNetscapeLine,
  netscapeDomain,
  netscapeExpiry,
};
