// Unit tests for the Netscape cookies.txt serializer (issue #73).
// Run with: bun test  (from extension/chrome)

import { describe, expect, test } from "bun:test";
import {
  cookieToNetscapeLine,
  netscapeDomain,
  netscapeExpiry,
  serializeNetscapeCookies,
} from "./cookies.js";

function ytCookie(overrides = {}) {
  return {
    name: "SID",
    value: "abc123",
    domain: ".youtube.com",
    path: "/",
    secure: true,
    httpOnly: false,
    session: false,
    hostOnly: false,
    expirationDate: 2000000000,
    ...overrides,
  };
}

describe("serializeNetscapeCookies", () => {
  test("emits the Netscape header", () => {
    const out = serializeNetscapeCookies([ytCookie()]);
    expect(out.startsWith("# Netscape HTTP Cookie File\n")).toBe(true);
  });

  test("data line has exactly 7 tab-separated fields", () => {
    const out = serializeNetscapeCookies([ytCookie()]);
    const dataLine = out.trim().split("\n").at(-1);
    expect(dataLine.split("\t")).toHaveLength(7);
  });

  test("domain-scoped cookie => leading dot + include-subdomains TRUE", () => {
    const { domain, includeSub } = netscapeDomain(ytCookie({ domain: "youtube.com", hostOnly: false }));
    expect(domain).toBe(".youtube.com");
    expect(includeSub).toBe("TRUE");
  });

  test("host-only cookie => bare domain + include-subdomains FALSE", () => {
    const { domain, includeSub } = netscapeDomain(
      ytCookie({ domain: ".youtube.com", hostOnly: true }),
    );
    expect(domain).toBe("youtube.com");
    expect(includeSub).toBe("FALSE");
  });

  test("httpOnly cookie gets the #HttpOnly_ prefix", () => {
    const line = cookieToNetscapeLine(ytCookie({ httpOnly: true }));
    expect(line.startsWith("#HttpOnly_.youtube.com\t")).toBe(true);
    // still 7 fields after stripping the prefix
    expect(line.replace("#HttpOnly_", "").split("\t")).toHaveLength(7);
  });

  test("session cookie => expiry 0", () => {
    expect(netscapeExpiry(ytCookie({ session: true }))).toBe(0);
    expect(netscapeExpiry(ytCookie({ expirationDate: undefined }))).toBe(0);
  });

  test("expiry is floored and 32-bit capped", () => {
    expect(netscapeExpiry(ytCookie({ expirationDate: 1700000000.9 }))).toBe(1700000000);
    expect(netscapeExpiry(ytCookie({ expirationDate: 9999999999 }))).toBe(2147483647);
  });

  test("tabs/newlines are stripped from the value", () => {
    const line = cookieToNetscapeLine(ytCookie({ value: "a\tb\nc" }));
    expect(line.split("\t")).toHaveLength(7);
    expect(line.endsWith("\tabc")).toBe(true);
  });

  test("cookies without a name are skipped", () => {
    const out = serializeNetscapeCookies([ytCookie({ name: "" }), ytCookie()]);
    expect(out.trim().split("\n").filter((l) => !l.startsWith("#")).length).toBe(1);
  });

  test("empty input yields header only", () => {
    const out = serializeNetscapeCookies([]);
    expect(out).toBe(
      "# Netscape HTTP Cookie File\n# Generated by the Karaoke Submitter extension. Do not edit.\n",
    );
  });
});
