// Unit tests for the Netscape cookies.txt serializer and the per-job request
// body builder (issues #73 + #77). Run with: bun test  (from extension/chrome)

import { describe, expect, test } from "bun:test";
import {
  buildJobBody,
  cookieToNetscapeLine,
  countYoutubeCookies,
  netscapeDomain,
  netscapeExpiry,
  serializeNetscapeCookies,
} from "./cookies.js";

function ytCookie(overrides = {}) {
  return {
    name: "SID",
    value: "abc123",
    domain: ".youtube.com",
    path: "/",
    secure: true,
    httpOnly: false,
    session: false,
    hostOnly: false,
    expirationDate: 2000000000,
    ...overrides,
  };
}

describe("serializeNetscapeCookies", () => {
  test("emits the Netscape header", () => {
    const out = serializeNetscapeCookies([ytCookie()]);
    expect(out.startsWith("# Netscape HTTP Cookie File\n")).toBe(true);
  });

  test("data line has exactly 7 tab-separated fields", () => {
    const out = serializeNetscapeCookies([ytCookie()]);
    const dataLine = out.trim().split("\n").at(-1);
    expect(dataLine.split("\t")).toHaveLength(7);
  });

  test("domain-scoped cookie => leading dot + include-subdomains TRUE", () => {
    const { domain, includeSub } = netscapeDomain(ytCookie({ domain: "youtube.com", hostOnly: false }));
    expect(domain).toBe(".youtube.com");
    expect(includeSub).toBe("TRUE");
  });

  test("host-only cookie => bare domain + include-subdomains FALSE", () => {
    const { domain, includeSub } = netscapeDomain(
      ytCookie({ domain: ".youtube.com", hostOnly: true }),
    );
    expect(domain).toBe("youtube.com");
    expect(includeSub).toBe("FALSE");
  });

  test("httpOnly cookie gets the #HttpOnly_ prefix", () => {
    const line = cookieToNetscapeLine(ytCookie({ httpOnly: true }));
    expect(line.startsWith("#HttpOnly_.youtube.com\t")).toBe(true);
    // still 7 fields after stripping the prefix
    expect(line.replace("#HttpOnly_", "").split("\t")).toHaveLength(7);
  });

  test("session cookie => expiry 0", () => {
    expect(netscapeExpiry(ytCookie({ session: true }))).toBe(0);
    expect(netscapeExpiry(ytCookie({ expirationDate: undefined }))).toBe(0);
  });

  test("expiry is floored and 32-bit capped", () => {
    expect(netscapeExpiry(ytCookie({ expirationDate: 1700000000.9 }))).toBe(1700000000);
    expect(netscapeExpiry(ytCookie({ expirationDate: 9999999999 }))).toBe(2147483647);
  });

  test("tabs/newlines are stripped from the value", () => {
    const line = cookieToNetscapeLine(ytCookie({ value: "a\tb\nc" }));
    expect(line.split("\t")).toHaveLength(7);
    expect(line.endsWith("\tabc")).toBe(true);
  });

  test("cookies without a name are skipped", () => {
    const out = serializeNetscapeCookies([ytCookie({ name: "" }), ytCookie()]);
    expect(out.trim().split("\n").filter((l) => !l.startsWith("#")).length).toBe(1);
  });

  test("empty input yields header only", () => {
    const out = serializeNetscapeCookies([]);
    expect(out).toBe(
      "# Netscape HTTP Cookie File\n# Generated by the Karaoke Submitter extension. Do not edit.\n",
    );
  });
});

describe("countYoutubeCookies", () => {
  test("counts only youtube.com cookies", () => {
    const cookies = [
      ytCookie(),
      ytCookie({ domain: ".google.com", name: "SAPISID" }),
      ytCookie({ domain: ".youtube.com", name: "HSID" }),
    ];
    expect(countYoutubeCookies(cookies)).toBe(2);
  });

  test("zero for google-only and for empty/undefined input", () => {
    expect(countYoutubeCookies([ytCookie({ domain: ".google.com" })])).toBe(0);
    expect(countYoutubeCookies([])).toBe(0);
    expect(countYoutubeCookies(undefined)).toBe(0);
  });
});

describe("buildJobBody", () => {
  test("always includes the url", () => {
    const body = buildJobBody({ url: "https://youtu.be/abc" });
    expect(body.url).toBe("https://youtu.be/abc");
  });

  test("includes source and title only when provided", () => {
    const withMeta = buildJobBody({
      url: "https://youtu.be/abc",
      source: "chrome-extension",
      title: "Rick Astley",
    });
    expect(withMeta.source).toBe("chrome-extension");
    expect(withMeta.title).toBe("Rick Astley");

    const bare = buildJobBody({ url: "https://youtu.be/abc" });
    expect("source" in bare).toBe(false);
    expect("title" in bare).toBe(false);
  });

  test("attaches youtube_cookies when youtube.com cookies are present", () => {
    const cookies = [
      ytCookie(),
      ytCookie({ domain: ".google.com", name: "SAPISID" }),
    ];
    const body = buildJobBody({ url: "https://youtu.be/abc", cookies });
    expect(typeof body.youtube_cookies).toBe("string");
    expect(body.youtube_cookies.startsWith("# Netscape HTTP Cookie File\n")).toBe(true);
    // The attached blob is exactly the serialized merged jar (yt + google).
    expect(body.youtube_cookies).toBe(serializeNetscapeCookies(cookies));
    expect(body.youtube_cookies.includes("\tSID\t")).toBe(true);
    expect(body.youtube_cookies.includes("\tSAPISID\t")).toBe(true);
  });

  test("omits youtube_cookies cleanly when there are no cookies", () => {
    const body = buildJobBody({ url: "https://youtu.be/abc", cookies: [] });
    expect("youtube_cookies" in body).toBe(false);
  });

  test("omits youtube_cookies when only non-youtube cookies are present", () => {
    const body = buildJobBody({
      url: "https://youtu.be/abc",
      cookies: [ytCookie({ domain: ".google.com", name: "SAPISID" })],
    });
    expect("youtube_cookies" in body).toBe(false);
  });

  test("omits youtube_cookies when cookies is missing/undefined", () => {
    const body = buildJobBody({ url: "https://youtu.be/abc" });
    expect("youtube_cookies" in body).toBe(false);
    expect(Object.keys(body)).toEqual(["url"]);
  });
});
