// Netscape cookies.txt serialization for the Karaoke Android submitter.
//
// Pure Kotlin port of extension/chrome/cookies.js — zero android.* imports so
// it runs as a plain JVM unit test. Data lines are byte-identical to the
// extension's output for identical input; only the header attribution comment
// (line 2) differs, and comment lines are ignored by every parser.
package com.befeast.karaoke.submitter.core

const val NETSCAPE_HEADER: String =
    "# Netscape HTTP Cookie File\n" +
        "# Generated by the Karaoke Android submitter. Do not edit.\n"

// yt-dlp treats a 0 expiry as a session cookie. Cap absurd far-future values
// to a 32-bit timestamp so the jar stays portable.
const val MAX_EXPIRY: Long = 2147483647L

/**
 * One cookie in the shape the Chrome `chrome.cookies` API exposes — the
 * serializer's semantics are defined against that shape (see cookies.js).
 * On Android the fields beyond (name, value, domain) are synthesized by
 * [CookieHeaderParser] or parsed from a pasted jar by [NetscapeJarParser].
 */
data class Cookie(
    val name: String,
    val value: String,
    val domain: String,
    val path: String = "/",
    val secure: Boolean = false,
    val httpOnly: Boolean = false,
    val hostOnly: Boolean = false,
    val session: Boolean = false,
    val expirationDate: Long? = null,
)

/** Resolved (domain, include-subdomains flag) pair for a Netscape data line. */
data class NetscapeDomain(val domain: String, val includeSub: String)

// Host-only cookies keep a bare domain and include-subdomains FALSE; otherwise
// the domain carries a leading dot and include-subdomains TRUE.
fun netscapeDomain(cookie: Cookie): NetscapeDomain {
    var domain = cookie.domain
    val includeSub = if (cookie.hostOnly) "FALSE" else "TRUE"
    if (!cookie.hostOnly && !domain.startsWith(".")) {
        domain = ".$domain"
    }
    if (cookie.hostOnly && domain.startsWith(".")) {
        domain = domain.substring(1)
    }
    return NetscapeDomain(domain, includeSub)
}

fun netscapeExpiry(cookie: Cookie): Long {
    if (cookie.session) {
        return 0
    }
    val value = cookie.expirationDate ?: return 0
    if (value <= 0) {
        return 0
    }
    return minOf(value, MAX_EXPIRY)
}

private val VALUE_STRIP = Regex("[\\t\\r\\n]")

// Serialize one cookie into a single Netscape data line, or null if it cannot
// be represented (missing name/domain). httpOnly cookies get yt-dlp's
// `#HttpOnly_` domain prefix so they survive the round-trip.
fun cookieToNetscapeLine(cookie: Cookie): String? {
    if (cookie.name.isEmpty() || cookie.domain.isEmpty()) {
        return null
    }
    val (domain, includeSub) = netscapeDomain(cookie)
    val prefix = if (cookie.httpOnly) "#HttpOnly_" else ""
    val path = cookie.path.ifEmpty { "/" }
    val secure = if (cookie.secure) "TRUE" else "FALSE"
    val expiry = netscapeExpiry(cookie)
    // Tab-separated, exactly 7 fields. Strip stray tabs/newlines from value so
    // a single cookie can never break the field layout.
    val value = cookie.value.replace(VALUE_STRIP, "")
    return listOf(
        "$prefix$domain",
        includeSub,
        path,
        secure,
        expiry.toString(),
        cookie.name,
        value,
    ).joinToString("\t")
}

// Serialize cookies into a Netscape cookies.txt blob: header + data lines +
// trailing newline iff any lines.
fun serializeNetscapeCookies(cookies: List<Cookie>): String {
    val lines = cookies.mapNotNull(::cookieToNetscapeLine)
    return NETSCAPE_HEADER + lines.joinToString("\n") + (if (lines.isNotEmpty()) "\n" else "")
}

// Count cookies whose domain belongs to youtube.com. The server requires at
// least one youtube.com cookie to treat a per-job jar as usable, so the app
// uses the same gate to decide whether to attach `youtube_cookies`.
fun countYoutubeCookies(cookies: List<Cookie>): Int =
    cookies.count { it.domain.contains("youtube.com") }
