package com.befeast.karaoke.submitter.core

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/** Port of extension/chrome/cookies.test.js serializer cases. */
class NetscapeCookiesTest {

    private fun ytCookie(
        name: String = "SID",
        value: String = "abc123",
        domain: String = ".youtube.com",
        path: String = "/",
        secure: Boolean = true,
        httpOnly: Boolean = false,
        session: Boolean = false,
        hostOnly: Boolean = false,
        expirationDate: Long? = 2000000000L,
    ) = Cookie(name, value, domain, path, secure, httpOnly, hostOnly, session, expirationDate)

    @Test
    fun `emits the Netscape header with the Android attribution line`() {
        val out = serializeNetscapeCookies(listOf(ytCookie()))
        assertTrue(out.startsWith("# Netscape HTTP Cookie File\n"))
        assertEquals(
            "# Generated by the Karaoke Android submitter. Do not edit.",
            out.lines()[1],
        )
    }

    @Test
    fun `data line has exactly 7 tab-separated fields`() {
        val out = serializeNetscapeCookies(listOf(ytCookie()))
        val dataLine = out.trim().lines().last()
        assertEquals(7, dataLine.split("\t").size)
    }

    @Test
    fun `domain-scoped cookie gets leading dot and include-subdomains TRUE`() {
        val (domain, includeSub) =
            netscapeDomain(ytCookie(domain = "youtube.com", hostOnly = false))
        assertEquals(".youtube.com", domain)
        assertEquals("TRUE", includeSub)
    }

    @Test
    fun `host-only cookie gets bare domain and include-subdomains FALSE`() {
        val (domain, includeSub) =
            netscapeDomain(ytCookie(domain = ".youtube.com", hostOnly = true))
        assertEquals("youtube.com", domain)
        assertEquals("FALSE", includeSub)
    }

    @Test
    fun `httpOnly cookie gets the HttpOnly_ prefix and still 7 fields`() {
        val line = cookieToNetscapeLine(ytCookie(httpOnly = true))!!
        assertTrue(line.startsWith("#HttpOnly_.youtube.com\t"))
        assertEquals(7, line.replace("#HttpOnly_", "").split("\t").size)
    }

    @Test
    fun `session or missing expiry maps to 0`() {
        assertEquals(0L, netscapeExpiry(ytCookie(session = true)))
        assertEquals(0L, netscapeExpiry(ytCookie(expirationDate = null)))
    }

    @Test
    fun `non-positive expiry maps to 0`() {
        assertEquals(0L, netscapeExpiry(ytCookie(expirationDate = 0L)))
        assertEquals(0L, netscapeExpiry(ytCookie(expirationDate = -5L)))
    }

    @Test
    fun `expiry is capped at 32-bit max`() {
        assertEquals(1700000000L, netscapeExpiry(ytCookie(expirationDate = 1700000000L)))
        assertEquals(2147483647L, netscapeExpiry(ytCookie(expirationDate = 9999999999L)))
    }

    @Test
    fun `tabs and newlines are stripped from the value`() {
        val line = cookieToNetscapeLine(ytCookie(value = "a\tb\nc\rd"))!!
        assertEquals(7, line.split("\t").size)
        assertTrue(line.endsWith("\tabcd"))
    }

    @Test
    fun `cookies without a name or domain are skipped`() {
        assertNull(cookieToNetscapeLine(ytCookie(name = "")))
        assertNull(cookieToNetscapeLine(ytCookie(domain = "")))
        val out = serializeNetscapeCookies(listOf(ytCookie(name = ""), ytCookie()))
        assertEquals(1, out.trim().lines().count { !it.startsWith("#") })
    }

    @Test
    fun `empty input yields header only without trailing data newline`() {
        assertEquals(NETSCAPE_HEADER, serializeNetscapeCookies(emptyList()))
    }

    @Test
    fun `countYoutubeCookies counts only youtube domains`() {
        val cookies = listOf(
            ytCookie(),
            ytCookie(domain = ".google.com", name = "SAPISID"),
            ytCookie(domain = ".youtube.com", name = "HSID"),
            ytCookie(domain = "music.youtube.com", name = "wide"),
        )
        assertEquals(3, countYoutubeCookies(cookies))
        assertEquals(0, countYoutubeCookies(listOf(ytCookie(domain = ".google.com"))))
        assertEquals(0, countYoutubeCookies(emptyList()))
    }
}
